### PR TITLE
Bump to Hazelcast 3.9.2

### PR DESCRIPTION
**Pull request by oscerd**

### CODE REVIEW

**Comment by pires** [comment]
@oscerd I name you maintainer of this repo. Do you want to maintain the hazelcast-kubernetes as well?

**Comment by oscerd** [comment]
Yes, sure. Will you take care of the release stuff?

**Comment by oscerd** [comment]
Thanks :-)

**Comment by pires** [comment]
You can do the release, since it relies on Github releases and not OSS Sonatype. Feel free to change the PGP key if you still want to sign it... maybe removing it doesn't hurt.

**Comment by oscerd** [comment]
I still have trouble when I run a mvn release:prepare and release:perform.. During the perform phase I get:

    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project hazelcast-kubernetes-bootstrapper: Failed to deploy artifacts: Could not transfer artifact com.github.pires:hazelcast-kubernetes-bootstrapper:jar:3.9.2 from/to sonatype-nexus-staging (https://oss.sonatype.org/service/local/staging/deploy/maven2): Failed to transfer file: https://oss.sonatype.org/service/local/staging/deploy/maven2/com/github/pires/hazelcast-kubernetes-bootstrapper/3.9.2/hazelcast-kubernetes-bootstrapper-3.9.2.jar. Return code is: 401, ReasonPhrase: Unauthorized. -> [Help 1]

**Comment by oscerd** [comment]
So it seems it relies on oss.sonatype

**Comment by pires** [comment]
Remove it from the POM.

**Comment by oscerd** [comment]
That's why you always need to look at the top of the POM and not only at the bottom.

**Comment by oscerd** [comment]
Still have the same problem. I remove the distributionManagement but we still rely on the Sonatype parent. I'll take a look tomorrow.

**Comment by oscerd** [comment]
Are you use mvn release:prepare and release:perform? Can you check with the actual POM if it works for you? Probably I have local Maven settings that are messing up this release.

**Comment by oscerd** [comment]
Done.

**Pull request merged**
