### PR TITLE
Upgrade Hazelcast to version 3.8

### PR DESCRIPTION
**Pull request by oscerd**

### CODE REVIEW

**Comment by oscerd** [comment]
Not sure you'll use the bootstrapper in the next hazelcast-kubernetes release. 

I noticed https://github.com/pires/hazelcast-kubernetes/issues/10 only after the PR was opened.

https://github.com/hazelcast/hazelcast-kubernetes

**Comment by pires** [comment]
The bootstrapper works fine for now so I'll keep it around. Thanks for your contribution!

**Comment by oscerd** [comment]
Love this project :-) My pleasure!

**Comment by pires** [comment]
Updated image and docs.

**Pull request merged**
